### ISSUE TITLE
Setting up a router with Cameron 

### ISSUE THREAD

**Issue by SungMinKim2795** [AguaClara/1-LPS#13]
Need wifi connection to set up ProCoDa in DeFrees for testing with coagulant.

**Comment by SungMinKim2795** [comment]
Will be talking to Carmen this week (2/26-3/2) to set a specific date and to see if we have to move the lab bench closer to the internet port

**Comment by sidneylok** [comment]
@sk2795  do you mean Cameron 😆

**Comment by sidneylok** [comment]
2/28 Spoke with Cameron about the spot we chose for the computer! He said he'll get the wire to the bench today (hopefully but at the latest Friday). It's not possible to have a router because he said he's not supposed to support that kind of behavior in DeFrees... so we'll just have to go with wired internet!

**Comment by ericamarroquin** [comment]
Cameron set up the wire today! Now we just need a computer..

**Comment by sidneylok** [comment]
We got a computer! But we still need to check with Cameron about whether it is up to date with the right software... will complete on Friday

**Comment by SungMinKim2795** [comment]
3.13 We met with Cameron and set up the computer in the DeFrees Lab!
